### PR TITLE
fix: disable `runtimeChunk` optimization

### LINKED ISSUE #47: Using runtimeChunk optimization causes compile failure
### Bug description

Since `instant-mocha` overrides `output.filename` to a constant `"main.js"`, an error is thrown by Webpack when using a separate runtime chunk, i.e. with `optimization.runtimeChunk = "single"`:

```
Error: Conflict: Multiple chunks emit assets to the same filename main.js (chunks main and runtime)
```

Since it's already overriding entries and other configurations, I would propose `runtimeChunk` also be unset as it is irrelevant for mocha tests.

### Reproduction

https://github.com/home-assistant/frontend/actions/runs/4648380830/jobs/8226042521

### Node.js package manager

yarn

### Environment

```shell
Node 16, Webpack 5.72.1, latest mocha and instant-mocha
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

### PR DESCRIPTION
**Pull request by steverep**
Fixes #47

### CODE REVIEW

File: src/lib/webpack.ts [hunk 1]
```diff
@@ -27,6 +27,11 @@ export function createWebpackCompiler(
 		libraryTarget: 'commonjs2',
 	};
 
+	// Turn off any separate runtime chunks since only "main.js" is output and imported by mocha
+	if (config?.optimization?.runtimeChunk) {
```
Comment (privatenumber) [inline src/lib/webpack.ts:31]:
```suggestion
	if (config.optimization?.runtimeChunk) {
```

**Comment by privatenumber** [comment]
Thanks!
